In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.impute import MissingIndicator,SimpleImputer

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])

In [5]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [6]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [9]:
x_train.head()

      Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

## Accuracy Check Before Missing Indicator is use

In [11]:
si=SimpleImputer()
x_train_si=si.fit_transform(x_train)
x_test_si=si.transform(x_test)

In [12]:
clf=LogisticRegression()
clf.fit(x_train_si,y_train)
y_pred=clf.predict(x_test_si)
accuracy_score(y_test,y_pred)

0.6145251396648045

## Accuracy Check After Missing Indicator is use

In [13]:
si=SimpleImputer(add_indicator=True)
x_train_si2=si.fit_transform(x_train)
x_test_si2=si.transform(x_test)

In [14]:
clf=LogisticRegression()
clf.fit(x_train_si2,y_train)
y_pred2=clf.predict(x_test_si2)
accuracy_score(y_test,y_pred2)

0.6312849162011173

In [16]:
x_train_si

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [17]:
x_train_si2

array([[ 40.        ,  27.7208    ,   0.        ],
       [  4.        ,  16.7       ,   0.        ],
       [ 47.        ,   9.        ,   0.        ],
       ...,
       [ 71.        ,  49.5042    ,   0.        ],
       [ 29.78590426, 221.7792    ,   1.        ],
       [ 29.78590426,  25.925     ,   1.        ]])

### last columns is True and False