## Multivariatr Imputation

In [29]:
import numpy as np
import pandas as pd

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [31]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [32]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [33]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [34]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [36]:
x_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [37]:
knn=KNNImputer()
x_train_knn=knn.fit_transform(x_train)
x_test_knn=knn.transform(x_test)

In [38]:
lr=LogisticRegression()
lr.fit(x_train_knn,y_train)

y_pred=lr.predict(x_test_knn)
accuracy_score(y_test,y_pred)

0.7039106145251397

## check the accuracy with another imputer

In [39]:
si=SimpleImputer()
x_train_si=si.fit_transform(x_train)
x_test_si=si.transform(x_test)

In [40]:
lr=LogisticRegression()
lr.fit(x_train_si,y_train)

y_pred2=lr.predict(x_test_si)
accuracy_score(y_test,y_pred2)

0.6927374301675978

In [45]:
for i in range(1, 20):  # Start from 1, go up to 19
    knn = KNNImputer(n_neighbors=i, weights='distance')
    x_train_knn = knn.fit_transform(x_train)
    x_test_knn = knn.transform(x_test)
    lr = LogisticRegression()
    lr.fit(x_train_knn, y_train)
    
    y_pred = lr.predict(x_test_knn)
    acc = accuracy_score(y_test, y_pred)
    print(f"K = {i}, Accuracy = {acc}")

K = 1, Accuracy = 0.6871508379888268
K = 2, Accuracy = 0.7150837988826816
K = 3, Accuracy = 0.7150837988826816
K = 4, Accuracy = 0.7094972067039106
K = 5, Accuracy = 0.7094972067039106
K = 6, Accuracy = 0.7039106145251397
K = 7, Accuracy = 0.7039106145251397
K = 8, Accuracy = 0.7039106145251397
K = 9, Accuracy = 0.7039106145251397
K = 10, Accuracy = 0.7039106145251397
K = 11, Accuracy = 0.7039106145251397
K = 12, Accuracy = 0.7039106145251397
K = 13, Accuracy = 0.7039106145251397
K = 14, Accuracy = 0.7039106145251397
K = 15, Accuracy = 0.7039106145251397
K = 16, Accuracy = 0.7039106145251397
K = 17, Accuracy = 0.7039106145251397
K = 18, Accuracy = 0.7039106145251397
K = 19, Accuracy = 0.7039106145251397

#### when K value is 2 and 3 then it give as a good result